global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'deep-oj-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'deep-oj-scheduler'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9091']
